spring.application.name=tasktracker

spring.mongodb.uri=mongodb+srv://root:Kalyan959%40@cluster0.uw01eou.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
spring.mongodb.database=task-tracker-test
